int mov=450;
int mov2=580;
int pmov;
int l;
int ubi1=75;
int ubi2=30;
int ancho;
float bolaX, bolaY, tamX, tamY;
float velx, vely, velop;
boolean victoria=true;
boolean derrota=true;
boolean pant1;
boolean pan0=true;
boolean creditos;
PImage[]fondos;
boolean[][] colision;
int numeroDeRect = 27;
void parametros() {
  pmov=440;
  bolaX=500;
  bolaY=300;
  tamX=20;
  tamY=20;
  velx=4;
  vely=4;
  velop=5;
  l=50;
  ancho=100;
  fondos=new PImage[8];
  fondos[0]=loadImage("PANT0.jpg");
  fondos[1]=loadImage("PANT01.jpg");
  fondos[2]=loadImage("pant1.jpg");
  fondos[3]=loadImage("victoria.jpg");
  fondos[4]=loadImage("derrota.jpg");
  fondos[5]=loadImage("creditos.jpg");
  fondos[6]=loadImage("pant2.jpg");
  fondos[7]=loadImage("plataforma.png");
  colision = new boolean[9][3];
}
